version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  pre_build:
    commands:
      - echo Set image variable
      - IMAGE_URI=344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Updating deployment manifest with new image URI...
      - sed -i "s|<IMAGE_URI>|$IMAGE_URI|g" kubernetes/deployment.yaml
      - echo Applying Kubernetes manifests...
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml
