version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 344249396000.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:latest .
      - docker tag 344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:latest 344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:latest:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:latest
      - docker push 344249396000.dkr.ecr.ap-south-1.amazonaws.com/vinrepo:$CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - kubernetes/*
